version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    image: super-blog
    command: bash -c "rm -f tmp/pids/server.pid && rails db:setup && rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db_data: