---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/articles":
    get:
      summary: list articles
      tags:
      - Public
      responses:
        '200':
          description: successful
    post:
      summary: create article
      tags:
      - Admin
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                category_id:
                  type: number
                tag_ids:
                  type: array
                  items:
                    type: string
              required:
              - title
              - body
  "/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Public
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    put:
      summary: update article
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete article
      tags:
      - Admin
      responses:
        '204':
          description: successful
  "/categories":
    get:
      summary: list categories
      tags:
      - Public
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
      - Admin
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Admin
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    put:
      summary: update category
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete category
      tags:
      - Admin
      responses:
        '204':
          description: successful
  "/articles/{article_id}/comments":
    parameters:
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      tags:
      - Public
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Admin
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                author_name:
                  type: string
                author_email:
                  type: string
              required:
              - text
              - author_name
              - author_email
  "/articles/{article_id}/comments/{id}":
    parameters:
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Public
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                author_name:
                  type: string
                author_email:
                  type: string
              required:
              - text
              - author_name
              - author_email
    put:
      summary: update comment
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                author_name:
                  type: string
                author_email:
                  type: string
              required:
              - text
              - author_name
              - author_email
    delete:
      summary: delete comment
      tags:
      - Admin
      responses:
        '204':
          description: successful
  "/tags":
    get:
      summary: list tags
      tags:
      - Admin
      responses:
        '200':
          description: successful
    post:
      summary: create tag
      tags:
      - Admin
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/tags/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show tag
      tags:
      - Admin
      responses:
        '200':
          description: successful
    patch:
      summary: update tag
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    put:
      summary: update tag
      tags:
      - Admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete tag
      tags:
      - Admin
      responses:
        '204':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
securitySchemes:
  Bearer:
    description: ''
    type: apiKey
    name: Authorization
    in: header
